apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing-deployment
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 911
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: syncthing
          image: lscr.io/linuxserver/syncthing:2.0.10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8384
            - containerPort: 22000
            - containerPort: 22000
              protocol: UDP
            - containerPort: 21027
              protocol: UDP
          env:
            - name: TZ
              value: "Europe/Warsaw"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: storage
              mountPath: /mnt/storage
            - name: run
              mountPath: /run
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: syncthing-config-pvc
        - name: storage
          persistentVolumeClaim:
            claimName: syncthing-storage-pvc
        - name: run
          emptyDir: {}
