apiVersion: v1
kind: Service
metadata:
  name: syncthing-service
  namespace: syncthing
spec:
  selector:
    app: syncthing
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8384
      targetPort: 8384
