apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backblaze-b2-secret
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: backblaze-b2-secret
    template:
      engineVersion: v2
      data:
        access_key_id: "{{ .access_key_id }}"
        access_key: "{{ .access_key }}"
        cloud: |
          [default]
          aws_access_key_id={{ .access_key_id }}
          aws_secret_access_key={{ .access_key }}
  data:
    - secretKey: access_key_id
      remoteRef:
        key: "fc46d156-60d7-4c2e-9a6c-b3660076d864"
    - secretKey: access_key
      remoteRef:
        key: "043a3b08-c216-4fcd-9373-b36600771459"
