apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/hotio/prowlarr:latest
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Warsaw
          ports:
            - containerPort: 9696
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
