apiVersion: gateway.networking.k8s.io/v1
kind: HttpRoute
metadata:
  name: http-to-https-redirect
  namespace: kube-system
spec:
  parentRefs:
    - name: default-gateway
      sectionName: http
  hostnames:
    - "*.nieradko.com"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
