apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ddns-cloudflare-api-token-secret
  namespace: cloudflare-ddns
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: api-token
      remoteRef:
        key: "32c9df07-daa0-4a9e-a85f-b36d00b581e8"
