kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-config-pvc
  namespace: media
spec:
  storageClassName: host-zfs-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
