apiVersion: v1
kind: Pod
metadata:
  name: zfs-shell
  namespace: kube-system
spec:
  nodeName: homelab
  hostIPC: true
  hostNetwork: true
  hostPID: true
  containers:
    - command: ["sleep", "infinity"]
      image: debian
      name: shell
      securityContext:
        privileged: true
