kubectl:
  image:
    repository: bitnamilegacy/kubectl
    tag: 1.33.4

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: homelab-velero-bucket
      config:
        region: eu-central-003
        s3Url: https://s3.eu-central-003.backblazeb2.com
        s3ForcePathStyle: true
        checksumAlgorithm: ""
  volumeSnapshotLocation:
    - name: default
      provider: openebs.io/zfspv-blockstore
      config:
        namespace: openebs
        provider: aws
        bucket: homelab-velero-bucket
        region: eu-central-003
        s3Url: https://s3.eu-central-003.backblazeb2.com
        s3ForcePathStyle: true
        checksumAlgorithm: ""

credentials:
  useSecret: true
  existingSecret: backblaze-b2-secret

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.0
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-openebs
    image: openebs/velero-plugin:3.6.0
    volumeMounts:
      - mountPath: /target
        name: plugins
