kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-pvc
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  storageClassName: host-zfs-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
