apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: openebs
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: test
      remoteRef:
        key: "437d7965-e65e-48c8-8bab-b364009de8e1"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
