apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-cloudflare-integration
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://github.com/KanarekLife/HomeLab.git
      targetRevision: HEAD
      path: kubernetes/cert-manager-cloudflare-integration
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
