apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://helm.cilium.io/
      chart: cilium
      targetRevision: "1.18.1"
      helm:
        releaseName: cilium
        valueFiles:
          - $repo/kubernetes/cilium/values.yaml
    - repoURL: https://github.com/KanarekLife/HomeLab.git
      targetRevision: HEAD
      ref: repo
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
