apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
      targetRevision: v1.3.0
      path: config/crd/standard
    - repoURL: https://github.com/KanarekLife/HomeLab.git
      targetRevision: HEAD
      path: kubernetes/gateway
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
