apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 11.0.0
      helm:
        releaseName: velero
        valueFiles:
          - $repo/kubernetes/velero/values.yaml
    - repoURL: https://github.com/KanarekLife/HomeLab.git
      targetRevision: HEAD
      ref: repo
    - repoURL: https://github.com/KanarekLife/HomeLab.git
      targetRevision: HEAD
      path: kubernetes/velero/manifests
  destination:
    name: in-cluster
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
