apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: linuxserver/qbittorrent:5.1.2
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: run
              mountPath: /run
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Warsaw
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: qb-web-ui
              containerPort: 8080
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
        - name: vpn
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "private internet access"
            - name: SERVER_REGIONS
              value: "Netherlands"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-secret
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-secret
                  key: password
            - name: DNS_ADDRESS
              value: "1.1.1.1"
            - name: DOT
              value: "off"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: run
          emptyDir: {}
