apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pia-vpn-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "6e85686f-abd7-4a34-96e2-b36500c66eb7"
    - secretKey: password
      remoteRef:
        key: "4cc96044-4951-47eb-abfd-b36500c69301"
