kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-pvc
spec:
  storageClassName: host-zfs-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
