kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-pvc
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  storageClassName: host-zfs-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
