apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: host-zfs-standard
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  recordsize: "1M"
  compression: "lz4"
  dedup: "off"
  fstype: "zfs"
  shared: "yes"
  poolname: "zfspv-pool"
