apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure Project
  sourceRepos:
    - https://github.com/KanarekLife/HomeLab.git
    - https://argoproj.github.io/argo-helm
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://helm.cilium.io/
    - https://github.com/alex1989hu/kubelet-serving-cert-approver
    - https://charts.jetstack.io
    - https://github.com/kubernetes-sigs/gateway-api.git
    - https://openebs.github.io/openebs
    - https://vmware-tanzu.github.io/helm-charts
    - https://seriohub.github.io/velero-helm
    - https://jellyfin.github.io/jellyfin-helm
    - https://charts.external-secrets.io
  destinations:
    - namespace: "*"
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
