apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-pg-secret
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: "d27c3cc1-2012-476d-9372-b36600e3f040"
    - secretKey: password
      remoteRef:
        key: "46e6a43f-512a-4e29-9914-b36600e402eb"
