apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: pg-username
      remoteRef:
        key: "d27c3cc1-2012-476d-9372-b36600e3f040"
    - secretKey: pg-password
      remoteRef:
        key: "46e6a43f-512a-4e29-9914-b36600e402eb"
    - secretKey: secret-key
      remoteRef:
        key: "55b3541d-ba17-4812-9d6a-b36600e3cc36"
    - secretKey: email-password
      remoteRef:
        key: "4305075d-04a1-4484-aece-b36601245b1d"
