kind: ConfigMap
apiVersion: v1
metadata:
  name: filebrowser-configmap
data:
  config.yaml: |
    server:
      sources:
        - path: /sources/media
          name: Media
        - path: /sources/downloads
          name: Downloads
        - path: /sources/prowlarr-config
          name: Prowlarr Config
        - path: /sources/qbittorrent-config
          name: qBittorrent Config
        - path: /sources/sonarr-config
          name: Sonarr Config
        - path: /sources/radarr-config
          name: Radarr Config
