apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: filebrowser
          image: gtstef/filebrowser:latest
          env:
            - name: TZ
              value: "Europe/Warsaw"
            - name: FILEBROWSER_DATABASE
              value: "/config/filebrowser.db"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /srv/media
            - name: qbittorrent-config
              mountPath: /srv/qbittorrent-config
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: filebrowser-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
