kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: filebrowser-config-pvc
spec:
  storageClassName: host-zfs-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
