apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  sources:
    - repoURL: https://github.com/KanarekLife/HomeLab.git
      targetRevision: HEAD
      path: kubernetes/applications/syncthing/manifests
      directory:
        recurse: true
  destination:
    name: in-cluster
    namespace: syncthing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
