apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: "1.18.2"
      helm:
        releaseName: cert-manager
        valueFiles:
          - $repo/kubernetes/infrastructure/cert-manager/meta/values.yaml
    - repoURL: https://github.com/KanarekLife/HomeLab.git
      targetRevision: HEAD
      ref: repo
    - repoURL: https://github.com/KanarekLife/HomeLab.git
      targetRevision: HEAD
      path: kubernetes/infrastructure/cert-manager/manifests
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
