apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dex-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: authentik-clientid
      remoteRef:
        key: 304edbef-a923-40af-8be0-b36600eda957
    - secretKey: authentik-clientsecret
      remoteRef:
        key: bf27831b-71d8-4ce6-a3ad-b36600edbc55
