kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bazarr-config-pvc
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: host-zfs-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
