apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-prod-cluster-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - name: https-argocd
      hostname: argocd.homelab.lan.nieradko.com
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-homelab-cert-tls
